<nav class="navbar navbar-expand-sm bg-primary navbar-dark">
  <div class="container-fluid">
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" href="user_add">add user</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="user_list">list users</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="index.php">login</a>
        </li>
    </ul>
  </div>
</nav>