<?php
if(!(isset($_SESSION["id"]))){
  header("Location: index.php");
  exit();
}
?>
<nav class="navbar navbar-expand-sm bg-primary navbar-dark">
  <div class="container-fluid">
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" href="user_add">add user</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="user_list">list users</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="login">login</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="logout">logout</a>
        </li>
  </div>
</nav>