<!DOCTYPE html>
<html lang="en">

<head>
  <title>user update</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"></script>
</head>



<div class="container mt-3 w3-border w3-padding w3-round ws-grey">
  <form method="post">
    <input type="hidden" name="action" value="user_list">
    <label for="email" class="fxorm-label">user with id:<?php echo $return["id"]?></label>
    <div class="mb-3 mt-3">
      <label for="email" class="fxorm-label">email:</label>
      <input type="text" class="form-control" style="margin-top:5px!important" id="upemail" placeholder="<?php echo $return["email"]?>" name="upemail">
    </div>
    <div class="mb-3">
      <label for="pwd" class="form-label">password:</label>
      <input type="password" class="form-control" id="uppassword" style="margin-top:5px!important" placeholder="Enter password" name="uppassword">
    </div>

    <button type="submit" class="btn btn-primary mb-3">submit</button>
  </form>
</div>


</html>