<!DOCTYPE html>
<html lang="en">

<head>
    <title>user list</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"></script>
</head>
<table class="table table-striped">
    <thead>
        <tr>
            <th>email</th>
            <th>edit</th>
            <th>delete</th>
        </tr>
    </thead>
    <tbody>
        <?php
        for ($i = 0; $i < 10; $i++) {
            echo "<tr>";
            echo "<td>" . "name" . +$i . "</td>";
            echo "<td>" . "lastname" . +$i . "</td>";
            echo "<td>" . "email" . +$i . "</td>";
            echo "</tr>";
        }
        ?>
    </tbody>
</table>

</html>