<!DOCTYPE html>
<html lang="en">

<head>
  <title>user update</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"></script>
</head>

<div class="container mt-3 w3-border w3-padding w3-round ws-grey">
  <form method="post">
    <input type="hidden" name="action" value="s">
    <div class="mb-3 mt-3">
      <label for="email" class="fxorm-label">email:</label>
      <input type="text" class="form-control" style="margin-top:5px!important" id="email" placeholder="Enter email" name="email">
    </div>
    <div class="mb-3">
      <label for="pwd" class="form-label">password:</label>
      <input type="password" class="form-control" id="name" style="margin-top:5px!important" placeholder="Enter password" name="password">
    </div>
    <div class="form-check mb-3">
      <label class="form-check-label">
        <input class="form-check-input" type="checkbox" name="remember"> Remember me
      </label>
    </div>

    <button type="submit" class="btn btn-primary mb-3">submit</button>
  </form>
</div>

</html>