<!DOCTYPE html>
<html lang="en">

<head>
  <title>add user</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"></script>
</head>

<body class="bg-secondary">
  <div class="container mt-3 w3-border w3-padding w3-round ws-grey">
    <form method="post">
      <input type="hidden" name="action" value="s">
      <div class="mb-3 mt-3">
        <label for="email" class="fxorm-label text-white">email:</label>
        <input type="text" class="form-control" style="margin-top:5px!important" id="email" placeholder="Enter email" name="email">
      </div>
      <div class="mb-3">
        <label for="pwd" class="form-label text-white">password:</label>
        <input type="password" class="form-control" id="password" style="margin-top:5px!important" placeholder="Enter password" name="password">
      </div>
      <div class="mb-3">
        <label for="pwd" class="form-label text-white">confirm password:</label>
        <input type="password" class="form-control " id="confirm_password" style="margin-top:5px!important" placeholder="confirm password" name="confirm_password">
      </div>
      <button type="submit" class="btn btn-primary mb-3">add user</button>
    </form>
  </div>
</body>

</html>